# Generated by Django 5.0 on 2024-03-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorterapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentExtentions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extention", models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
