# Generated by Django 5.0 on 2024-03-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorterapp", "0002_documentextentions"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentExtention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extention", models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImageExtention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extention", models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoExtention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extention", models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name="DocumentExtentions",
            new_name="AudioExtention",
        ),
    ]
