# Generated by Django 4.2.2 on 2024-03-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorterapp", "0003_documentextention_imageextention_videoextention_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZipFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="audioextention",
            name="extention",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="documentextention",
            name="extention",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="imageextention",
            name="extention",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="videoextention",
            name="extention",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
